name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Code quality
        continue-on-error: false
        run: ./gradlew ktlintCheck

      - name: Unit tests
        continue-on-error: false
        run: ./gradlew test

      - name: Build
        continue-on-error: false
        run: ./gradlew build