name: Integration tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
  workflow_call:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Run integration tests
        env:
          TURSO_TOKEN: ${{ secrets.TURSO_TOKEN }}
          TURSO_ORGANIZATION: ${{ secrets.TURSO_ORGANIZATION }}
        continue-on-error: false
        run: ./gradlew integrationTest
